# spring 环境配置
spring:
  servlet:
    multipart:
      # 上传文件大小限制
      max-file-size: 200MB
      max-request-size: 500MB
  # 模版配置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
  # 数据库配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.4.208.134:3306/sei_edm?characterEncoding=utf8&useSSL=false
    username: sei
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  cache:
    redis:
      time-to-live: 20s
  redis:
    host: 10.4.208.132
    port: 6379
    password: ZmkDbgaua3Rso33T
    database: 0
  data:
    mongodb:
      uri: mongodb://edm_dev:lAjrgwbT0xqWNT8LVmmOAs1f@10.4.208.132:27017/edm
#  cloud:
#    service-registry: # 本机不自动注册到服务列表
#      auto-registration:
#        enabled: false

logging:
  level:
    org:
      apache:
        kafka:
          clients:
            NetworkClient: error
sei:
  # 核心配置
  edm:
    model: mongo
    store-path: /Users/chaoma/work_space/0_temp/
    jod-converter:
      enabled: true
#      office-home: /opt/openoffice4
      office-home: /Applications/OpenOffice.app/Contents
#      office-home: /Applications/LibreOffice.app/Contents
#      port-numbers: 8100,8101,8102
      port-numbers: 8100
      max-tasks-per-process: 100
    # 识别相关配置
    ocr:
      # 条码匹配前缀
      match-prefix: rcs,sei,nhd,gwm
      # 配置tessdata的安装路径表示启用tessdata识别
#      tessdata-path:
  http:
    filter:
      ignore-auth-url: /pdfjs/web/,/base/base.html,/pageoffice/,/preview/

server:
  servlet:
    context-path: /edm
